'use client';

import { ChangeFeedItem, ActiveSourceStat } from './types';

export const INITIAL_CHANGE_ITEMS: ChangeFeedItem[] = [
  // Earlier Today
  {
    id: 'chg-1',
    title: 'Rahul replied to your email',
    contextSubtitle: 'Re: Project Alpha update',
    sourceId: 'gmail',
    sourceName: 'Gmail',
    timeSection: 'Earlier Today',
    timestamp: '15m ago',
    importance: 'important',
    category: 'messages',
    isRead: false,
    iconType: 'mail',
    personName: 'Rahul Patel',
    personAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    badgeDotColor: 'purple',
    whatChanged: 'Rahul confirmed client approval for Project Alpha Phase 1, but noted a pending deliverable timeline question regarding Friday\'s release.',
    whyItMatters: 'Your team\'s active work stream assumes delivery format v2. Replying now prevents duplicate work and resolves the conflict before the Friday 10:00 AM sync.',
    relatedContext: [
      {
        sourceId: 'gmail',
        sourceName: 'Gmail',
        title: 'Re: Project Alpha update',
        snippet: '"We need to align on whether the Phase 1 spec goes out on Friday or if we hold for the API payload signoff..."',
        timestamp: '15m ago',
      },
      {
        sourceId: 'drive',
        sourceName: 'Google Drive',
        title: 'Project_Alpha_Proposal_v2.docx',
        snippet: 'Updated section 4.2 with finalized client milestone milestones.',
        timestamp: '1h ago',
      },
    ],
    recommendedAction: {
      label: 'Prepare response →',
      actionType: 'prepare_response',
    },
  },
  {
    id: 'chg-2',
    title: 'Project Alpha Sync rescheduled',
    contextSubtitle: 'Now on Friday, May 16 at 10:00 AM',
    sourceId: 'calendar',
    sourceName: 'Google Calendar',
    timeSection: 'Earlier Today',
    timestamp: '32m ago',
    importance: 'important',
    category: 'calendar',
    isRead: false,
    iconType: 'calendar',
    badgeDotColor: 'blue',
    whatChanged: 'Project Alpha Sync was moved 2 hours later to Friday, May 16 at 10:00 AM by the team coordinator.',
    whyItMatters: 'This resolves the previous conflict with your 8:30 AM Focus Block and provides a 30-minute buffer before the client briefing.',
    relatedContext: [
      {
        sourceId: 'calendar',
        sourceName: 'Google Calendar',
        title: 'Project Alpha Sync (Rescheduled)',
        snippet: 'Friday, May 16 · 10:00 AM – 10:45 AM (5 attendees confirmed)',
        timestamp: '32m ago',
      },
      {
        sourceId: 'gmail',
        sourceName: 'Gmail',
        title: 'Calendar Update Notification',
        snippet: 'Invitation updated with Google Meet link.',
        timestamp: '32m ago',
      },
    ],
    recommendedAction: {
      label: 'Review conflict →',
      actionType: 'review_conflict',
    },
  },
  {
    id: 'chg-3',
    title: 'Proposal v2 updated',
    contextSubtitle: '"Project_Alpha_Proposal_v2.docx"',
    sourceId: 'drive',
    sourceName: 'Google Drive',
    timeSection: 'Earlier Today',
    timestamp: '1h ago',
    importance: 'relevant',
    category: 'documents',
    isRead: false,
    iconType: 'doc',
    personName: 'Sarah Jenkins',
    personAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    badgeDotColor: 'emerald',
    whatChanged: 'Sarah updated pricing tables and timeline milestones in section 4.2 of "Project_Alpha_Proposal_v2.docx".',
    whyItMatters: 'Reflects revised scope discussed in leadership sync. Ready for your final review before sending to the client.',
    relatedContext: [
      {
        sourceId: 'drive',
        sourceName: 'Google Drive',
        title: 'Project_Alpha_Proposal_v2.docx',
        snippet: 'Last edited by Sarah Jenkins 1 hour ago • 4 pages updated.',
        timestamp: '1h ago',
      },
    ],
    recommendedAction: {
      label: 'Open document →',
      actionType: 'open_source',
    },
  },
  {
    id: 'chg-4',
    title: 'New task assigned to you',
    contextSubtitle: 'Review pricing strategy',
    sourceId: 'asana',
    sourceName: 'Asana',
    timeSection: 'Earlier Today',
    timestamp: '2h ago',
    importance: 'relevant',
    category: 'tasks',
    isRead: true,
    iconType: 'task',
    badgeDotColor: 'amber',
    whatChanged: 'Assigned by David Chen with priority High and due date of Thursday at 5:00 PM.',
    whyItMatters: 'Required milestone before final contract dispatch to enterprise client account.',
    relatedContext: [
      {
        sourceId: 'asana',
        sourceName: 'Asana',
        title: 'Review pricing strategy',
        snippet: 'Due Thursday May 15 · Priority: High · Project: Commercial Strategy',
        timestamp: '2h ago',
      },
    ],
    recommendedAction: {
      label: 'View task →',
      actionType: 'view_task',
    },
  },

  // Yesterday
  {
    id: 'chg-5',
    title: 'You were mentioned by Priya in Slack',
    contextSubtitle: '#project-alpha',
    sourceId: 'slack',
    sourceName: 'Slack',
    timeSection: 'Yesterday',
    timestamp: 'Yesterday, 4:45 PM',
    importance: 'relevant',
    category: 'mentions',
    isRead: true,
    iconType: 'mention',
    personName: 'Priya Sharma',
    personAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    badgeDotColor: 'blue',
    whatChanged: 'Priya tagged you: "@Aryan could you confirm if the updated Figma mockups match the technical feasibility doc?"',
    whyItMatters: 'Design team is waiting for API payload approval before locking Sprint 28 scope.',
    relatedContext: [
      {
        sourceId: 'slack',
        sourceName: 'Slack',
        title: '#project-alpha channel',
        snippet: 'Priya: "@Aryan could you confirm if the updated Figma mockups match the technical feasibility doc?"',
        timestamp: 'Yesterday, 4:45 PM',
      },
    ],
    recommendedAction: {
      label: 'Reply in Slack →',
      actionType: 'open_source',
    },
  },
  {
    id: 'chg-6',
    title: 'Q3 Planning notes updated',
    contextSubtitle: 'Team added new comments',
    sourceId: 'notion',
    sourceName: 'Notion',
    timeSection: 'Yesterday',
    timestamp: 'Yesterday, 2:15 PM',
    importance: 'informational',
    category: 'documents',
    isRead: true,
    iconType: 'doc',
    additionalPersonCount: 2,
    badgeDotColor: 'purple',
    whatChanged: 'Alex and Marcus added 4 comments regarding budget allocation for Q3 infrastructure scaling.',
    whyItMatters: 'Summarizes headcount and cloud compute projections ahead of next week\'s executive review.',
    relatedContext: [
      {
        sourceId: 'notion',
        sourceName: 'Notion',
        title: 'Q3 Planning Notes',
        snippet: '4 new inline comments on Infrastructure & Cloud Scaling Budget section.',
        timestamp: 'Yesterday, 2:15 PM',
      },
    ],
    recommendedAction: {
      label: 'View comments →',
      actionType: 'open_source',
    },
  },

  // Grouped Item Example (Project Alpha - 3 related events)
  {
    id: 'grp-alpha',
    title: 'Project Alpha',
    contextSubtitle: '3 related changes · Client reply, calendar shift, and proposal update',
    sourceId: 'gmail',
    sourceName: 'Gmail · Calendar · Drive',
    timeSection: 'Yesterday',
    timestamp: 'Yesterday, 11:30 AM',
    importance: 'important',
    category: 'all',
    isRead: true,
    iconType: 'mail',
    badgeDotColor: 'purple',
    isGroup: true,
    groupProjectName: 'Project Alpha',
    subChanges: [
      {
        id: 'sub-1',
        title: 'Client confirmed Phase 1 scope',
        contextSnippet: 'Email confirmation from Rahul regarding target specs.',
        sourceId: 'gmail',
        sourceName: 'Gmail',
        timestamp: 'Yesterday, 11:30 AM',
        personName: 'Rahul Patel',
        personAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
      },
      {
        id: 'sub-2',
        title: 'Product Sync moved to Friday',
        contextSnippet: 'Google Calendar invite updated to 10:00 AM.',
        sourceId: 'calendar',
        sourceName: 'Google Calendar',
        timestamp: 'Yesterday, 11:15 AM',
      },
      {
        id: 'sub-3',
        title: 'Proposal v2 uploaded to Drive',
        contextSnippet: 'Sarah pushed updated commercial terms.',
        sourceId: 'drive',
        sourceName: 'Google Drive',
        timestamp: 'Yesterday, 9:40 AM',
        personName: 'Sarah Jenkins',
        personAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
      },
    ],
    whatChanged: '3 correlated events detected around Project Alpha: client email reply, meeting reschedule, and proposal v2 update.',
    whyItMatters: 'NEXORBIT detected these are all part of the same delivery milestone rather than disconnected isolated alerts.',
    relatedContext: [
      {
        sourceId: 'gmail',
        sourceName: 'Gmail',
        title: 'Project Alpha Thread',
        snippet: 'Thread containing 4 messages between you and Rahul.',
        timestamp: 'Yesterday, 11:30 AM',
      },
    ],
    recommendedAction: {
      label: 'Review group context →',
      actionType: 'review_conflict',
    },
  },

  // Additional items for Load More
  {
    id: 'chg-7',
    title: 'GitHub PR #142: Core API Pipeline merged',
    contextSubtitle: 'Merged into main by Alex • 12 commits',
    sourceId: 'github',
    sourceName: 'GitHub',
    timeSection: 'Earlier',
    timestamp: 'May 12, 4:10 PM',
    importance: 'informational',
    category: 'tasks',
    isRead: true,
    iconType: 'code',
    personName: 'Alex Chen',
    personAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    badgeDotColor: 'emerald',
    whatChanged: 'Alex merged PR #142 optimizing database query batching and response caching.',
    whyItMatters: 'Improves response latency by 35% ahead of client load testing.',
    relatedContext: [
      {
        sourceId: 'github',
        sourceName: 'GitHub',
        title: 'PR #142: Core API Pipeline',
        snippet: '12 commits · 48 files changed · All automated CI checks passed.',
        timestamp: 'May 12, 4:10 PM',
      },
    ],
    recommendedAction: {
      label: 'Open PR in GitHub →',
      actionType: 'open_source',
    },
  },
  {
    id: 'chg-8',
    title: 'Security Questionnaire draft shared',
    contextSubtitle: '"Enterprise_Security_Audit_2026.pdf"',
    sourceId: 'drive',
    sourceName: 'Google Drive',
    timeSection: 'Earlier',
    timestamp: 'May 11, 2:30 PM',
    importance: 'relevant',
    category: 'documents',
    isRead: true,
    iconType: 'doc',
    badgeDotColor: 'amber',
    whatChanged: 'Uploaded by Security Compliance team for annual SOC2 verification.',
    whyItMatters: 'Requires IT security approval before June 1.',
    relatedContext: [
      {
        sourceId: 'drive',
        sourceName: 'Google Drive',
        title: 'Enterprise_Security_Audit_2026.pdf',
        snippet: 'PDF document · 18 pages · Pending review',
        timestamp: 'May 11, 2:30 PM',
      },
    ],
    recommendedAction: {
      label: 'Open document →',
      actionType: 'open_source',
    },
  },
];

export const MOCK_MOST_ACTIVE_SOURCES: ActiveSourceStat[] = [
  { sourceId: 'gmail', sourceName: 'Gmail', count: 6 },
  { sourceId: 'calendar', sourceName: 'Google Calendar', count: 4 },
  { sourceId: 'drive', sourceName: 'Google Drive', count: 3 },
  { sourceId: 'slack', sourceName: 'Slack', count: 3 },
  { sourceId: 'notion', sourceName: 'Notion', count: 2 },
];

export const WEEKLY_ACTIVITY_DATA = [
  { day: 'M', count: 12, active: false },
  { day: 'T', count: 15, active: false },
  { day: 'W', count: 14, active: false },
  { day: 'T', count: 18, active: true }, // Current active day in reference screenshot
  { day: 'F', count: 11, active: false },
  { day: 'S', count: 7, active: false },
  { day: 'S', count: 9, active: false },
];
