import { DailyPlanItem, PrioritySettings } from './types';

export const INITIAL_TODAY_PLAN_ITEMS: DailyPlanItem[] = [
  {
    id: 'plan-1',
    time: '9:30 AM',
    duration: '30m',
    durationMinutes: 30,
    title: 'Project Alpha Sync',
    description: 'Discuss updates, risks and next steps.',
    sourceId: 'calendar',
    sourceName: 'Google Calendar',
    priority: 'important',
    type: 'meeting',
    actionLabel: 'Join meeting',
    actionType: 'join_meeting',
    colorTheme: 'purple',
    whyPrioritized: 'Critical team sync before afternoon deliverables. 4 attendees awaiting alignment.',
    contextEvidence: [
      {
        source: 'Google Calendar',
        snippet: 'Project Alpha Sync: 9:30 - 10:00 AM • Google Meet link attached • 4 confirmed',
        timestamp: 'Today, 9:30 AM',
      },
      {
        source: 'Gmail',
        snippet: 'Rahul: "Let\'s finalize the timeline on the 9:30 AM call today."',
        timestamp: '1 hour ago',
      },
    ],
  },
  {
    id: 'plan-2',
    time: '10:30 AM',
    duration: '60m',
    durationMinutes: 60,
    title: 'Review client feedback',
    description: 'Go through the latest feedback from Rahul.',
    sourceId: 'gmail',
    sourceName: 'Gmail',
    priority: 'high',
    type: 'email',
    actionLabel: 'Open email',
    actionType: 'open_email',
    colorTheme: 'blue',
    whyPrioritized: 'Direct client feedback from Rahul on pricing & milestones; response expected by 1:00 PM.',
    contextEvidence: [
      {
        source: 'Gmail',
        snippet: 'Thread: Re: Enterprise Scope & Milestones — 4 new annotated comments from client',
        timestamp: '2 hours ago',
      },
    ],
  },
  {
    id: 'plan-3',
    time: '11:30 AM',
    duration: '45m',
    durationMinutes: 45,
    title: 'Proposal v2 final review',
    description: 'Review the updated proposal before sharing.',
    sourceId: 'drive',
    sourceName: 'Google Drive',
    priority: 'high',
    type: 'document',
    actionLabel: 'Open file',
    actionType: 'open_file',
    colorTheme: 'emerald',
    whyPrioritized: 'Google Drive document updated with new slide deck and legal disclaimers.',
    contextEvidence: [
      {
        source: 'Google Drive',
        snippet: 'Proposal_v2_Final.pdf modified by Sarah Jenkins (Product Strategy)',
        timestamp: '3 hours ago',
      },
    ],
  },
  {
    id: 'plan-4',
    time: '12:15 PM',
    duration: '45m',
    durationMinutes: 45,
    title: 'Lunch Break',
    description: 'Recharge and relax.',
    priority: 'low',
    type: 'break',
    actionLabel: 'Take break',
    actionType: 'take_break',
    colorTheme: 'amber',
    whyPrioritized: 'Optimal scheduled recharge window to prevent afternoon cognitive fatigue.',
  },
  {
    id: 'plan-5',
    time: '1:00 PM',
    duration: '60m',
    durationMinutes: 60,
    title: 'Prepare pricing strategy',
    description: 'Build analysis and talking points.',
    sourceId: 'notion',
    sourceName: 'Notion',
    priority: 'medium',
    type: 'notes',
    actionLabel: 'Open notes',
    actionType: 'open_notes',
    colorTheme: 'indigo',
    whyPrioritized: 'Required talking points for Tier 1 enterprise pricing structure before afternoon follow-ups.',
    contextEvidence: [
      {
        source: 'Notion',
        snippet: 'Page: "Q3 Enterprise Pricing Matrix & Tier Adjustments" (Draft)',
        timestamp: 'Yesterday, 6:15 PM',
      },
    ],
  },
  {
    id: 'plan-6',
    time: '2:30 PM',
    duration: '30m',
    durationMinutes: 30,
    title: 'Follow up with Rahul',
    description: 'Align on requirements and timelines.',
    sourceId: 'gmail',
    sourceName: 'Gmail',
    priority: 'medium',
    type: 'email',
    actionLabel: 'Send email',
    actionType: 'send_email',
    colorTheme: 'blue',
    whyPrioritized: 'Scheduled follow-up email incorporating feedback resolved during morning reviews.',
    contextEvidence: [
      {
        source: 'Gmail',
        snippet: 'Draft queued in Gmail with updated attachments and SLA terms',
        timestamp: 'Today, 8:45 AM',
      },
    ],
  },
  {
    id: 'plan-7',
    time: '3:15 PM',
    duration: '45m',
    durationMinutes: 45,
    title: 'GitHub PR Review: Auth Migration',
    description: 'Review security patch and test coverage in PR #142.',
    sourceId: 'github',
    sourceName: 'GitHub',
    priority: 'medium',
    type: 'task',
    actionLabel: 'Open PR',
    actionType: 'review_task',
    colorTheme: 'slate',
    whyPrioritized: 'Requested review from backend engineering team on OAuth token handling.',
    contextEvidence: [
      {
        source: 'GitHub',
        snippet: 'PR #142: feat(auth): migrate token storage to encrypted session store',
        timestamp: '4 hours ago',
      },
    ],
  },
  {
    id: 'plan-8',
    time: '4:15 PM',
    duration: '45m',
    durationMinutes: 45,
    title: 'Daily Wrap-up & Tomorrow Planning',
    description: 'Log accomplishments and review pending threads.',
    priority: 'low',
    type: 'task',
    actionLabel: 'Review summary',
    actionType: 'open_notes',
    colorTheme: 'indigo',
    whyPrioritized: 'Autonomous daily synthesis to update NEXORBIT memory for tomorrow morning.',
  },
];

export const INITIAL_PRIORITY_SETTINGS: PrioritySettings = {
  deadlineSensitive: true,
  meetingsAndCollab: true,
  clientWork: true,
  deepWorkBias: true,
  quickWins: false,
};

export const MOCK_WHY_THIS_PLAN = {
  summary:
    'NEXORBIT analyzed 11 active tasks, 3 calendar events, 14 recent emails, and 6 modified documents across your connected workspace.',
  drivers: [
    {
      title: 'Immediate Calendar Constraints',
      description: 'Project Alpha Sync starts at 9:30 AM with 4 stakeholders. Prioritized first for immediate alignment.',
      iconName: 'calendar',
      impact: 'High Impact',
    },
    {
      title: 'Client Communications Pressure',
      description: 'Rahul sent feedback on the proposal requiring a response before 1:00 PM.',
      iconName: 'mail',
      impact: 'Time-Critical',
    },
    {
      title: 'Protected Deep Work Window',
      description: 'Your biological peak energy window (9:00 AM – 11:00 AM) is protected for strategic reviews.',
      iconName: 'sparkles',
      impact: 'Focus Window',
    },
    {
      title: 'Goal Alignment',
      description: 'Directly advances "Enterprise Client Onboarding" Q3 primary milestone.',
      iconName: 'target',
      impact: 'Goal Progress',
    },
  ],
};
